### PR TITLE
add logo folder inside docs folder

### PR DESCRIPTION
**Pull request by Debiday**
Added logo folder inside docs folder to keep main folder clean.

### CODE REVIEW

**Comment by Debiday** [comment]
Hi @mariannovotny, sorry for making duplicate [PR #466 ](https://github.com/G-Research/siembol/pull/466). This is the right one. Can I trouble you to check if this is appropriate? Thank you 😊

**Comment by mariannovotny** [comment]
Hi @Debiday Thanks for PR. Do we need  and want to support ai format if we include open format svg?

**Comment by stackedsax** [comment]
I think we have them because our design shop sends us a bundle of assets with .ai files.  However, I think it's a reasonable industry-standard thing to include.  My understanding is that .svg files don't have some of the print information that .ai files contain.  So, like, when we want to print out Siembol handbooks and manuals :D

**Comment by mariannovotny** [comment]
Do we really need this file in main branch of git repository? Not all files related to siembol we are storing there.

**Comment by Debiday** [comment]
Thanks @mariannovotny for getting back on this, and @stackedsax I thought the same. The .ai file gives the logo more flexibility, e.g. if any part of the logo needs to be tweaked or the colors need to be changed for some specific collateral, .ai file would have the layers to make a quick edit. The .ai file generates the .svg, so it would have more information I believe. Unless of course, your concern might be related to a copyright issue for the .ai file? 

Hm @mariannovotny, if this is not the right branch, can you point me to the right one? Thank you :)

**Comment by tabathad** [comment]
Chiming in to say that the Illustrator file can be easily converted to a PDF file that retains the details needed for high-quality printing with the benefit of additional accessibility since not everyone has access to Adobe Illustrator.  If that's the direction you'd like to go, let me know and I can help convert .ai to .pdf. 

Regarding rademark or copyright, I don't foresee that as being a huge problem regarding the logo so long as we actively police brand usage and defend against misuse when we find it.

**Comment by stackedsax** [comment]
I think it's more that any future designers who work with the logo will
probably want to work with an .ai file.  I think it should just go in the
main branch.

Cheers,

-Alex

**Comment by mariannovotny** [comment]
Thanks all for your comments and your effort. I am just thinking what is purpose of these logo files? They are not used in code or documentation.

We would like to use main branch for code and documentation and not to mix with other siembol content (presentations, marketing materials) that can be published on webpage. I can image to implement it on webpage under download logos? 

In my opinion gh-pages branch is better for this purpose.

**Comment by Debiday** [comment]
Thanks @mariannovotny, that makes sense. Taking everyone's concerns into consideration, we can add .pdf files into the logos from @tabathad, and put the entire logo collection in the gh-pages branch. @stackedsax, is that alright with you?

**Pull request closed without merging**
