### PR TITLE
Adding news item to News section

### PR DESCRIPTION
**Pull request by c-rindi**
Adding 3rd news item to News section.

### CODE REVIEW

**Comment by stackedsax** [comment]
Looks mostly good, but I think "BHEurope2021.png" needs to be added to the PR to make that image show up, yeah?

**Comment by c-rindi** [comment]
The other posts didn’t need the image in the PR - they are located in the media file (https://github.com/G-Research/siembol/tree/gh-pages/docs/media/news/title), so I just copied that.

**Comment by stackedsax** [comment]
Cool, looks like the image you want is in https://github.com/G-Research/siembol/tree/gh-pages/docs/media/news/title after all, so this looks good to me.

👍

**Review by stackedsax — APPROVED** [review]
👍

**Review by mariannovotny — APPROVED** [review]

**Pull request merged**
